server:
  port: 80
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/

mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml
